// projectsData.js

export const projectsData = [
  {
    id: 1,
    title: [
      "Dashboard 1- Cost Analysis, ",
      "Dashboard 2- Projected Vs Actual Costs by project",
      "Dashboard 3 - Projected Vs Actual Costs",
    ],
    description: ["", "", ""],
    image: "images/portfolio/construction/image-1.png",
    imagesCarousel: [
      [
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
      ],
    ],
    tags: ["Construction", "Dashboard", "Cost Analysis"],
  },
  {
    id: 2,
    title: [
      "Dashboard 2- Projected Vs Actual Costs by project",
      "Dashboard 3 - Projected Vs Actual Costs",
      "Dashboard 1- Cost Analysis, ",
    ],
    description: ["", "", ""],
    image: "images/portfolio/construction/image-2.png",
    imagesCarousel: [
      [
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
      ],
      [
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
      ],
    ],
    tags: ["Construction", "Dashboard", "Cost Analysis"],
  },
  {
    id: 3,
    title: [
      "Dashboard 3 - Projected Vs Actual Costs",
      "Dashboard 1- Cost Analysis, ",
      "Dashboard 2- Projected Vs Actual Costs by project",
    ],
    description: ["", "", ""],
    image: "images/portfolio/construction/image-3.png",
    imagesCarousel: [
      [
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
      ],
      [
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
      ],
    ],
    tags: ["Construction", "Dashboard", "Cost Analysis"],
  },
  // Ajoutez d'autres projets ici...
  {
    id: 4,
    title: [
      "Map View of all shipments",
      "Board Sample - Outbounds shipments",
      "CRM - Leads Management Board",
      "CRM - Sales Pipeline & Costing",
      "CRM - Freight Rates Management",
    ],
    description: [
      "View of Export, Import, domestic shipments on a world map where data can be seen and updated directly from the map or on the Monday.com board.",
      "Used by an International Relocation company to track what needs to be done for each shipment. This board was displayed on a large screen for the team to have an overview of the status of each job",
      "A board allowing to manage all leads by salesperson. This board is part of a CRM workflow with advanced automations in place",
      "Sales people able to generate a quotation from this board by first inputting various cost associated to each shipment",
      "Freight rates analysis coming from various suppliers that are used by the salespersons before generating quotations for clients.",
    ],
    image: "images/portfolio/logistic/image-1.png",
    imagesCarousel: [
      ["images/portfolio/logistic/image-1.png"],
      ["images/portfolio/logistic/image-2.png"],
      ["images/portfolio/logistic/image-3.png"],
      ["images/portfolio/logistic/image-4.png"],
      ["images/portfolio/logistic/image-5.png"],
    ],
    tags: ["Logistic", "Map"],
  },
  {
    id: 5,
    title: [
      "Board Sample - Outbounds shipments",
      "CRM - Leads Management Board",
      "CRM - Sales Pipeline & Costing",
      "CRM - Freight Rates Management",
      "Map View of all shipments",
    ],
    description: [
      "Used by an International Relocation company to track what needs to be done for each shipment. This board was displayed on a large screen for the team to have an overview of the status of each job",
      "A board allowing to manage all leads by salesperson. This board is part of a CRM workflow with advanced automations in place",
      "Sales people able to generate a quotation from this board by first inputting various cost associated to each shipment",
      "Freight rates analysis coming from various suppliers that are used by the salespersons before generating quotations for clients.",
      "View of Export, Import, domestic shipments on a world map where data can be seen and updated directly from the map or on the Monday.com board.",
    ],
    image: "images/portfolio/logistic/image-2.png",
    imagesCarousel: [
      ["images/portfolio/logistic/image-2.png"],
      ["images/portfolio/logistic/image-3.png"],
      ["images/portfolio/logistic/image-4.png"],
      ["images/portfolio/logistic/image-5.png"],
      ["images/portfolio/logistic/image-1.png"],
    ],
    tags: ["Logistic", "Operations/Checklist"],
  },
  {
    id: 6,
    title: [
      "CRM - Leads Management Board",
      "CRM - Sales Pipeline & Costing",
      "CRM - Freight Rates Management",
      "Map View of all shipments",
      "Board Sample - Outbounds shipments",
    ],
    description: [
      "A board allowing to manage all leads by salesperson. This board is part of a CRM workflow with advanced automations in place",
      "Sales people able to generate a quotation from this board by first inputting various cost associated to each shipment",
      "Freight rates analysis coming from various suppliers that are used by the salespersons before generating quotations for clients.",
      "View of Export, Import, domestic shipments on a world map where data can be seen and updated directly from the map or on the Monday.com board.",
      "Used by an International Relocation company to track what needs to be done for each shipment. This board was displayed on a large screen for the team to have an overview of the status of each job",
    ],
    image: "images/portfolio/logistic/image-3.png",
    imagesCarousel: [
      ["images/portfolio/logistic/image-3.png"],
      ["images/portfolio/logistic/image-4.png"],
      ["images/portfolio/logistic/image-5.png"],
      ["images/portfolio/logistic/image-1.png"],
      ["images/portfolio/logistic/image-2.png"],
    ],
    tags: ["Logistic", "CRM"],
  },
  {
    id: 7,
    title: [
      "CRM - Sales Pipeline & Costing",
      "CRM - Freight Rates Management",
      "Map View of all shipments",
      "Board Sample - Outbounds shipments",
      "CRM - Leads Management Board",
    ],
    description: [
      "Sales people able to generate a quotation from this board by first inputting various cost associated to each shipment",
      "Freight rates analysis coming from various suppliers that are used by the salespersons before generating quotations for clients.",
      "View of Export, Import, domestic shipments on a world map where data can be seen and updated directly from the map or on the Monday.com board.",
      "Used by an International Relocation company to track what needs to be done for each shipment. This board was displayed on a large screen for the team to have an overview of the status of each job",
      "A board allowing to manage all leads by salesperson. This board is part of a CRM workflow with advanced automations in place",
    ],
    image: "images/portfolio/logistic/image-4.png",
    imagesCarousel: [
      ["images/portfolio/logistic/image-4.png"],
      ["images/portfolio/logistic/image-5.png"],
      ["images/portfolio/logistic/image-1.png"],
      ["images/portfolio/logistic/image-2.png"],
      ["images/portfolio/logistic/image-3.png"],
    ],
    tags: ["Logistic", "CRM"],
  },
  {
    id: 8,
    title: [
      "CRM - Freight Rates Management",
      "Map View of all shipments",
      "Board Sample - Outbounds shipments",
      "CRM - Leads Management Board",
      "CRM - Sales Pipeline & Costing",
    ],
    description: [
      "Freight rates analysis coming from various suppliers that are used by the salespersons before generating quotations for clients.",
      "View of Export, Import, domestic shipments on a world map where data can be seen and updated directly from the map or on the Monday.com board.",
      "Used by an International Relocation company to track what needs to be done for each shipment. This board was displayed on a large screen for the team to have an overview of the status of each job",
      "A board allowing to manage all leads by salesperson. This board is part of a CRM workflow with advanced automations in place",
      "Sales people able to generate a quotation from this board by first inputting various cost associated to each shipment",
    ],
    image: "images/portfolio/logistic/image-5.png",
    imagesCarousel: [
      ["images/portfolio/logistic/image-5.png"],
      ["images/portfolio/logistic/image-1.png"],
      ["images/portfolio/logistic/image-2.png"],
      ["images/portfolio/logistic/image-3.png"],
      ["images/portfolio/logistic/image-4.png"],
    ],
    tags: ["Logistic", "CRM"],
  },
  // Manufacturing
  {
    id: 9,
    title: [
      "QR Codes Scan",
      "Sample Manufacturing Board 1",
      "Sample Manufacturing Board 2",
      "Sample Automations in a Manufacturing Board",
      "Inventory Management Board Sample",
    ],
    description: [
      "Scanning QR codes at the Factory changing automatically statuses and timers on the Monday board.",
      "Orders status for each station changing after the employees canning the orders at the factory.",
      "",
      "",
      "",
    ],
    image: "images/portfolio/manufacturing/image-1.png",
    imagesCarousel: [
      ["images/portfolio/manufacturing/image-1.png"],
      ["images/portfolio/manufacturing/image-2.png"],
      ["images/portfolio/manufacturing/image-3.png"],
      ["images/portfolio/manufacturing/image-4.png"],
      ["images/portfolio/manufacturing/image-5.png"],
    ],
    tags: ["Manufacturing", "Integrations"],
  },
  {
    id: 10,
    title: [
      "Sample Manufacturing Board 1",
      "Sample Manufacturing Board 2",
      "Sample Automations in a Manufacturing Board",
      "Inventory Management Board Sample",
      "QR Codes Scan",
    ],
    description: [
      "Orders status for each station changing after the employees canning the orders at the factory.",
      "",
      "",
      "",
      "Scanning QR codes at the Factory changing automatically statuses and timers on the Monday board.",
    ],
    image: "images/portfolio/manufacturing/image-2.png",
    imagesCarousel: [
      ["images/portfolio/manufacturing/image-2.png"],
      ["images/portfolio/manufacturing/image-3.png"],
      ["images/portfolio/manufacturing/image-4.png"],
      ["images/portfolio/manufacturing/image-5.png"],
      ["images/portfolio/manufacturing/image-1.png"],
    ],
    tags: ["Manufacturing", "Operations/Checklist", "Time tracking"],
  },
  {
    id: 11,
    title: [
      "Sample Manufacturing Board 2",
      "Sample Automations in a Manufacturing Board",
      "Inventory Management Board Sample",
      "QR Codes Scan",
      "Sample Manufacturing Board 1",
    ],
    description: [
      "",
      "",
      "",
      "Scanning QR codes at the Factory changing automatically statuses and timers on the Monday board.",
      "Orders status for each station changing after the employees canning the orders at the factory.",
    ],
    image: "images/portfolio/manufacturing/image-3.png",
    imagesCarousel: [
      ["images/portfolio/manufacturing/image-3.png"],
      ["images/portfolio/manufacturing/image-4.png"],
      ["images/portfolio/manufacturing/image-5.png"],
      ["images/portfolio/manufacturing/image-1.png"],
      ["images/portfolio/manufacturing/image-2.png"],
    ],
    tags: ["Manufacturing", "Operations/Checklist", "Time tracking"],
  },
  {
    id: 12,
    title: [
      "Sample Automations in a Manufacturing Board",
      "Inventory Management Board Sample",
      "QR Codes Scan",
      "Sample Manufacturing Board 1",
      "Sample Manufacturing Board 2",
    ],
    description: [
      "",
      "",
      "Scanning QR codes at the Factory changing automatically statuses and timers on the Monday board.",
      "Orders status for each station changing after the employees canning the orders at the factory.",
      "",
    ],
    image: "images/portfolio/manufacturing/image-4.png",
    imagesCarousel: [
      ["images/portfolio/manufacturing/image-4.png"],
      ["images/portfolio/manufacturing/image-5.png"],
      ["images/portfolio/manufacturing/image-1.png"],
      ["images/portfolio/manufacturing/image-2.png"],
      ["images/portfolio/manufacturing/image-3.png"],
    ],
    tags: ["Manufacturing", "Automations"],
  },
  {
    id: 13,
    title: [
      "Inventory Management Board Sample",
      "QR Codes Scan",
      "Sample Manufacturing Board 1",
      "Sample Manufacturing Board 2",
      "Sample Automations in a Manufacturing Board",
    ],
    description: [
      "",
      "Scanning QR codes at the Factory changing automatically statuses and timers on the Monday board.",
      "Orders status for each station changing after the employees canning the orders at the factory.",
      "",
      "",
    ],
    image: "images/portfolio/manufacturing/image-5.png",
    imagesCarousel: [
      ["images/portfolio/manufacturing/image-5.png"],
      ["images/portfolio/manufacturing/image-1.png"],
      ["images/portfolio/manufacturing/image-2.png"],
      ["images/portfolio/manufacturing/image-3.png"],
      ["images/portfolio/manufacturing/image-4.png"],
    ],
    tags: ["Manufacturing", "Inventory"],
  },
  {
    id: 14,
    title: [
      "Live Dashboard - Daily Deliveries",
      "Dashboard 2",
      "Dashboard 3",
      "Dashboard Sample 1 - CRM Suppliers",
    ],
    description: [
      "Tracking orders made by customers on different channels. Reporting was done daily, weekly and monthly. Reporting was made per location as this restaurant had several branches.",
      "We were able to tracking on the 2 bottom widgets the orders by geographical zones, and by type of customers",
      "",
      "",
    ],
    image: "images/portfolio/restaurant/image-1.png",
    imagesCarousel: [
      ["images/portfolio/restaurant/image-1.png"],
      ["images/portfolio/restaurant/image-2.png"],
      ["images/portfolio/restaurant/image-3.png"],
      ["images/portfolio/restaurant/image-4.png"],
    ],
    tags: ["Restaurant", "Dashboard", "Orders tracking"],
  },
  {
    id: 15,
    title: [
      "Dashboard 2",
      "Dashboard 3",
      "Dashboard Sample 1 - CRM Suppliers",
      "Live Dashboard - Daily Deliveries",
    ],
    description: [
      "We were able to tracking on the 2 bottom widgets the orders by geographical zones, and by type of customers",
      "",
      "",
      "Tracking orders made by customers on different channels. Reporting was done daily, weekly and monthly. Reporting was made per location as this restaurant had several branches.",
    ],
    image: "images/portfolio/restaurant/image-2.png",
    imagesCarousel: [
      ["images/portfolio/restaurant/image-2.png"],
      ["images/portfolio/restaurant/image-3.png"],
      ["images/portfolio/restaurant/image-4.png"],
      ["images/portfolio/restaurant/image-1.png"],
    ],
    tags: ["Restaurant", "Dashboard", "Orders tracking"],
  },
  {
    id: 16,
    title: [
      "Dashboard 3",
      "Dashboard Sample 1 - CRM Suppliers",
      "Live Dashboard - Daily Deliveries",
      "Dashboard 2",
    ],
    description: [
      "",
      "",
      "Tracking orders made by customers on different channels. Reporting was done daily, weekly and monthly. Reporting was made per location as this restaurant had several branches.",
      "We were able to tracking on the 2 bottom widgets the orders by geographical zones, and by type of customers",
    ],
    image: "images/portfolio/restaurant/image-3.png",
    imagesCarousel: [
      ["images/portfolio/restaurant/image-3.png"],
      ["images/portfolio/restaurant/image-4.png"],
      ["images/portfolio/restaurant/image-1.png"],
      ["images/portfolio/restaurant/image-2.png"],
    ],
    tags: ["Restaurant", "Dashboard", "Orders tracking"],
  },
  {
    id: 17,
    title: [
      "Dashboard Sample 1 - CRM Suppliers",
      "Live Dashboard - Daily Deliveries",
      "Dashboard 2",
      "Dashboard 3",
    ],
    description: [
      "",
      "Tracking orders made by customers on different channels. Reporting was done daily, weekly and monthly. Reporting was made per location as this restaurant had several branches.",
      "We were able to tracking on the 2 bottom widgets the orders by geographical zones, and by type of customers",
      "",
    ],
    image: "images/portfolio/restaurant/image-4.png",
    imagesCarousel: [
      ["images/portfolio/restaurant/image-4.png"],
      ["images/portfolio/restaurant/image-1.png"],
      ["images/portfolio/restaurant/image-2.png"],
      ["images/portfolio/restaurant/image-3.png"],
    ],
    tags: ["Restaurant", "CRM", "Orders tracking", "Directory"],
  },
  // Real Estate
  {
    id: 18,
    title: [
      "Sample Board 1- Vacancy Checklist",
      "Sample Board 1- Vacancy Checklist",
      "Sample Integrations - Automated Emails",
      "Sample Automations 1",
      "Sample Automations 2",
    ],
    description: [
      "Fully automated checklist based on the move-out date allowing to track and manage hundreds of properties",
      "",
      "When an element of the checklist is about to be due or overdue, emails are sent automatically to the PIC and Managers based on a set of rules",
      "",
      "",
    ],
    image: "images/portfolio/real-estate/image-1.png",
    imagesCarousel: [
      ["images/portfolio/real-estate/image-1.png"],
      ["images/portfolio/real-estate/image-2.png"],
      ["images/portfolio/real-estate/image-3.png"],
      ["images/portfolio/real-estate/image-4.png"],
      ["images/portfolio/real-estate/image-5.png"],
    ],
    tags: ["Real Estate", "Operations/Checklist"],
  },
  {
    id: 19,
    title: [
      "Sample Board 1- Vacancy Checklist",
      "Sample Integrations - Automated Emails",
      "Sample Automations 1",
      "Sample Automations 2",
      "Sample Board 1- Vacancy Checklist",
    ],
    description: [
      "",
      "When an element of the checklist is about to be due or overdue, emails are sent automatically to the PIC and Managers based on a set of rules",
      "",
      "",
      "Fully automated checklist based on the move-out date allowing to track and manage hundreds of properties",
    ],
    image: "images/portfolio/real-estate/image-2.png",
    imagesCarousel: [
      ["images/portfolio/real-estate/image-2.png"],
      ["images/portfolio/real-estate/image-3.png"],
      ["images/portfolio/real-estate/image-4.png"],
      ["images/portfolio/real-estate/image-5.png"],
      ["images/portfolio/real-estate/image-1.png"],
    ],
    tags: ["Real Estate", "Operations/Checklist"],
  },
  {
    id: 20,
    title: [
      "Sample Integrations - Automated Emails",
      "Sample Automations 1",
      "Sample Automations 2",
      "Sample Board 1- Vacancy Checklist",
      "Sample Board 1- Vacancy Checklist",
    ],
    description: [
      "When an element of the checklist is about to be due or overdue, emails are sent automatically to the PIC and Managers based on a set of rules",
      "",
      "",
      "Fully automated checklist based on the move-out date allowing to track and manage hundreds of properties",
      "",
    ],
    image: "images/portfolio/real-estate/image-3.png",
    imagesCarousel: [
      ["images/portfolio/real-estate/image-3.png"],
      ["images/portfolio/real-estate/image-4.png"],
      ["images/portfolio/real-estate/image-5.png"],
      ["images/portfolio/real-estate/image-1.png"],
      ["images/portfolio/real-estate/image-2.png"],
    ],
    tags: ["Real Estate", "Automations"],
  },
  {
    id: 21,
    title: [
      "Sample Automations 1",
      "Sample Automations 2",
      "Sample Board 1- Vacancy Checklist",
      "Sample Board 1- Vacancy Checklist",
      "Sample Integrations - Automated Emails",
    ],
    description: [
      "",
      "",
      "Fully automated checklist based on the move-out date allowing to track and manage hundreds of properties",
      "",
      "When an element of the checklist is about to be due or overdue, emails are sent automatically to the PIC and Managers based on a set of rules",
    ],
    image: "images/portfolio/real-estate/image-4.png",
    imagesCarousel: [
      ["images/portfolio/real-estate/image-4.png"],
      ["images/portfolio/real-estate/image-5.png"],
      ["images/portfolio/real-estate/image-1.png"],
      ["images/portfolio/real-estate/image-2.png"],
      ["images/portfolio/real-estate/image-3.png"],
    ],
    tags: ["Real Estate", "Automations"],
  },
  {
    id: 22,
    title: [
      "Sample Automations 2",
      "Sample Board 1- Vacancy Checklist",
      "Sample Board 1- Vacancy Checklist",
      "Sample Integrations - Automated Emails",
      "Sample Automations 1",
    ],
    description: [
      "",
      "Fully automated checklist based on the move-out date allowing to track and manage hundreds of properties",
      "",
      "When an element of the checklist is about to be due or overdue, emails are sent automatically to the PIC and Managers based on a set of rules",
      "",
    ],
    image: "images/portfolio/real-estate/image-5.png",
    imagesCarousel: [
      ["images/portfolio/real-estate/image-5.png"],
      ["images/portfolio/real-estate/image-1.png"],
      ["images/portfolio/real-estate/image-2.png"],
      ["images/portfolio/real-estate/image-3.png"],
      ["images/portfolio/real-estate/image-4.png"],
    ],
    tags: ["Real Estate", "Automations"],
  },
  // Construction
  {
    id: 23,
    title: [
      "Dashboard 1- Cost Analysis, ",
      "Dashboard 2- Projected Vs Actual Costs by project",
      "Dashboard 3 - Projected Vs Actual Costs",
    ],
    description: ["", "", ""],
    image: "images/portfolio/construction/image-1.png",
    imagesCarousel: [
      [
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
      ],
    ],
    tags: ["Construction", "Dashboard", "Cost Analysis"],
  },
  {
    id: 24,
    title: [
      "Dashboard 2- Projected Vs Actual Costs by project",
      "Dashboard 3 - Projected Vs Actual Costs",
      "Dashboard 1- Cost Analysis, ",
    ],
    description: ["", "", ""],
    image: "images/portfolio/construction/image-2.png",
    imagesCarousel: [
      [
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
      ],
      [
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
      ],
    ],
    tags: ["Construction", "Dashboard", "Cost Analysis"],
  },
  {
    id: 25,
    title: [
      "Dashboard 3 - Projected Vs Actual Costs",
      "Dashboard 1- Cost Analysis, ",
      "Dashboard 2- Projected Vs Actual Costs by project",
    ],
    description: ["", "", ""],
    image: "images/portfolio/construction/image-3.png",
    imagesCarousel: [
      [
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
      ],
      [
        "images/portfolio/construction/image-1.png",
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
      ],
      [
        "images/portfolio/construction/image-2.png",
        "images/portfolio/construction/image-3.png",
        "images/portfolio/construction/image-1.png",
      ],
    ],
    tags: ["Construction", "Dashboard", "Cost Analysis"],
  },
  // Marketing
  {
    id: 26,
    title: [
      "Dashboard Sample 1- Client Overview",
      "Sample Board 1- Marekting Agency",
      "Sample Board 2- Video Production",
      "Sample Board 3- Video Production",
      "Sample Automations 1",
    ],
    description: [
      "Used by a Marketing Agency to see what are the activity for a particular account. The leads are connected from the client's website so that everything can be managed within Monday.com",
      "Sample Board 1- Marketing Agency",
      "",
      "",
      "",
    ],
    image: "images/portfolio/marketing-agency/image-1.png",
    imagesCarousel: [
      ["images/portfolio/marketing-agency/image-1.png"],
      ["images/portfolio/marketing-agency/image-2.png"],
      ["images/portfolio/marketing-agency/image-3.png"],
      ["images/portfolio/marketing-agency/image-4.png"],
      ["images/portfolio/marketing-agency/image-5.png"],
    ],
    tags: ["Marketing", "Dashboard"],
  },
  {
    id: 27,
    title: [
      "Sample Board 1- Marekting Agency",
      "Sample Board 2- Video Production",
      "Sample Board 3- Video Production",
      "Sample Automations 1",
      "Dashboard Sample 1- Client Overview",
    ],
    description: [
      "Sample Board 1- Marketing Agency",
      "",
      "",
      "",
      "Used by a Marketing Agency to see what are the activity for a particular account. The leads are connected from the client's website so that everything can be managed within Monday.com",
    ],
    image: "images/portfolio/marketing-agency/image-2.png",
    imagesCarousel: [
      ["images/portfolio/marketing-agency/image-2.png"],
      ["images/portfolio/marketing-agency/image-3.png"],
      ["images/portfolio/marketing-agency/image-4.png"],
      ["images/portfolio/marketing-agency/image-5.png"],
      ["images/portfolio/marketing-agency/image-1.png"],
    ],
    tags: ["Marketing", "Project Management"],
  },
  {
    id: 28,
    title: [
      "Sample Board 2- Video Production",
      "Sample Board 3- Video Production",
      "Sample Automations 1",
      "Dashboard Sample 1- Client Overview",
      "Sample Board 1- Marekting Agency",
    ],
    description: [
      "",
      "",
      "",
      "Used by a Marketing Agency to see what are the activity for a particular account. The leads are connected from the client's website so that everything can be managed within Monday.com",
      "Sample Board 1- Marketing Agency",
    ],
    image: "images/portfolio/marketing-agency/image-3.png",
    imagesCarousel: [
      ["images/portfolio/marketing-agency/image-3.png"],
      ["images/portfolio/marketing-agency/image-4.png"],
      ["images/portfolio/marketing-agency/image-5.png"],
      ["images/portfolio/marketing-agency/image-1.png"],
      ["images/portfolio/marketing-agency/image-2.png"],
    ],
    tags: ["Marketing", "Project Management"],
  },
  {
    id: 29,
    title: [
      "Sample Board 3- Video Production",
      "Sample Automations 1",
      "Dashboard Sample 1- Client Overview",
      "Sample Board 1- Marekting Agency",
      "Sample Board 2- Video Production",
    ],
    description: [
      "",
      "",
      "Used by a Marketing Agency to see what are the activity for a particular account. The leads are connected from the client's website so that everything can be managed within Monday.com",
      "Sample Board 1- Marketing Agency",
      "",
    ],
    image: "images/portfolio/marketing-agency/image-4.png",
    imagesCarousel: [
      ["images/portfolio/marketing-agency/image-4.png"],
      ["images/portfolio/marketing-agency/image-5.png"],
      ["images/portfolio/marketing-agency/image-1.png"],
      ["images/portfolio/marketing-agency/image-2.png"],
      ["images/portfolio/marketing-agency/image-3.png"],
    ],
    tags: ["Marketing", "Project Management"],
  },
  {
    id: 30,
    title: [
      "Sample Automations 1",
      "Dashboard Sample 1- Client Overview",
      "Sample Board 1- Marekting Agency",
      "Sample Board 2- Video Production",
      "Sample Board 3- Video Production",
    ],
    description: [
      "",
      "Used by a Marketing Agency to see what are the activity for a particular account. The leads are connected from the client's website so that everything can be managed within Monday.com",
      "Sample Board 1- Marketing Agency",
      "",
      "",
    ],
    image: "images/portfolio/marketing-agency/image-5.png",
    imagesCarousel: [
      ["images/portfolio/marketing-agency/image-5.png"],
      ["images/portfolio/marketing-agency/image-1.png"],
      ["images/portfolio/marketing-agency/image-2.png"],
      ["images/portfolio/marketing-agency/image-3.png"],
      ["images/portfolio/marketing-agency/image-4.png"],
    ],
    tags: ["Marketing", "Automations"],
  },
  // Timetracking
  {
    id: 31,
    title: [
      "Time tracking report on Toggl integrated with Monday",
      "Time tracking report on Toggl integrated with Monday",
      "2 Way Sync of the tasks between Monday and Toggl",
      "Sample o the scenario we have build using Make.com",
    ],
    description: ["", "", "", ""],
    image: "images/portfolio/time-tracking/image-1.png",
    imagesCarousel: [
      ["images/portfolio/time-tracking/image-1.png"],
      ["images/portfolio/time-tracking/image-2.png"],
      ["images/portfolio/time-tracking/image-3.png"],
      ["images/portfolio/time-tracking/image-4.png"],
    ],
    tags: ["Marketing", "Time tracking"],
  },
  {
    id: 32,
    title: [
      "Time tracking report on Toggl integrated with Monday",
      "2 Way Sync of the tasks between Monday and Toggl",
      "Sample o the scenario we have build using Make.com",
      "Time tracking report on Toggl integrated with Monday",
    ],
    description: ["", "", "", ""],
    image: "images/portfolio/time-tracking/image-2.png",
    imagesCarousel: [
      ["images/portfolio/time-tracking/image-2.png"],
      ["images/portfolio/time-tracking/image-3.png"],
      ["images/portfolio/time-tracking/image-4.png"],
      ["images/portfolio/time-tracking/image-1.png"],
    ],
    tags: ["Marketing", "Time tracking"],
  },
  {
    id: 33,
    title: [
      "2 Way Sync of the tasks between Monday and Toggl",
      "Sample o the scenario we have build using Make.com",
      "Time tracking report on Toggl integrated with Monday",
      "Time tracking report on Toggl integrated with Monday",
    ],
    description: ["", "", "", ""],
    image: "images/portfolio/time-tracking/image-3.png",
    imagesCarousel: [
      ["images/portfolio/time-tracking/image-3.png"],
      ["images/portfolio/time-tracking/image-4.png"],
      ["images/portfolio/time-tracking/image-1.png"],
      ["images/portfolio/time-tracking/image-2.png"],
    ],
    tags: ["Marketing", "Time tracking"],
  },
  {
    id: 34,
    title: [
      "Sample o the scenario we have build using Make.com",
      "Time tracking report on Toggl integrated with Monday",
      "Time tracking report on Toggl integrated with Monday",
      "2 Way Sync of the tasks between Monday and Toggl",
    ],
    description: ["", "", "", ""],
    image: "images/portfolio/time-tracking/image-4.png",
    imagesCarousel: [
      ["images/portfolio/time-tracking/image-4.png"],
      ["images/portfolio/time-tracking/image-1.png"],
      ["images/portfolio/time-tracking/image-2.png"],
      ["images/portfolio/time-tracking/image-3.png"],
    ],
    tags: ["Marketing", "Time tracking", "Make.com"],
  },
];
